source "https://rubygems.org"

gem "webrick", "~> 1.7"
gem "jekyll", "~> 4.2"
gem "jekyll-environment-variables"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-toc"
gem "jekyll-last-modified-at"
gem "jekyll-sitemap"